include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# Julia versions

julia:1.5:
  extends:
    - .julia:1.5
    - .test
  tags:
    - intel


# special tests

debug:
  extends:
    - .julia:1.5
    - .test
  tags:
    - intel
  script:
    - julia --project -g2 -e 'using Pkg;
                              Pkg.instantiate();
                              Pkg.build();
                              Pkg.test(; coverage=true);'

validation:
  extends:
    - .julia:1.5
    - .test
  tags:
    - intel
  variables:
    ZE_ENABLE_VALIDATION_LAYER: '1'
    ZE_ENABLE_PARAMETER_VALIDATION: '1'
  script:
    - julia --project -g2 -e 'using Pkg;
                              Pkg.instantiate();
                              Pkg.build();
                              Pkg.test(; coverage=true);'


# other tasks

coverage:
  extends:
    - .julia:1.5
    - .coverage
