include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:latest

variables:
  JULIA_DEBUG: 'oneL0'


# Julia versions

julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - intel

julia:1.4:
  extends:
    - .julia:1.4
    - .test
  tags:
    - intel

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  allow_failure: true
  tags:
    - intel


# other tasks

coverage:
  extends:
    - .julia:1.3
    - .coverage
