[general]
library_name = "liboneapi_support"
output_file_path = "../lib/support/liboneapi_support.jl"


[codegen]
use_ccall_macro = true

[api.onemklXgemmBatched.argtypes]
4 = "ZePtr{Int64}"
5 = "ZePtr{Int64}"
6 = "ZePtr{Int64}"
7 = "ZePtr{T}"
8 = "ZePtr{Ptr{T}}"
9 = "ZePtr{Int64}"
10 = "ZePtr{Ptr{T}}"
11 = "ZePtr{Int64}"
12 = "ZePtr{T}"
13 = "ZePtr{Ptr{T}}"
14 = "ZePtr{Int64}"
16 = "ZePtr{Int64}"

[api.onemklXtrsmBatched.argtypes]
6 = "ZePtr{Int64}"
7 = "ZePtr{Int64}"
8 = "ZePtr{T}"
9 = "ZePtr{Ptr{T}}"
10 = "ZePtr{Int64}"
11 = "ZePtr{Ptr{T}}"
12 = "ZePtr{Int64}"
14 = "ZePtr{Int64}"

[api.onemklXgemmBatchStrided.argtypes]
7 = "T"
8 = "ZePtr{T}"
11 = "ZePtr{T}"
14 = "T"
15 = "ZePtr{T}"

[api.onemklXgemm.argtypes]
7 = "T"
8 = "ZePtr{T}"
10 = "ZePtr{T}"
12 = "T"
13 = "ZePtr{T}"

[api.onemklXsymm.argtypes]
6 = "T"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "T"
12 = "ZePtr{T}"

[api.onemklXsyrk.argtypes]
6 = "T"
7 = "ZePtr{T}"
9 = "T"
10 = "ZePtr{T}"

[api.onemklXsyr2k.argtypes]
6 = "T"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "T"
12 = "ZePtr{T}"

[api.onemklXtrmm.argtypes]
8 = "T"
9 = "ZePtr{T}"
11 = "ZePtr{T}"

[api.onemklXtrsm.argtypes]
8 = "T"
9 = "ZePtr{T}"
11 = "ZePtr{T}"

[api.onemklXhemm.argtypes]
6 = "T"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "T"
12 = "ZePtr{T}"

[api.onemklXherk.argtypes]
6 = "T"
7 = "ZePtr{T}"
9 = "T"
10 = "ZePtr{T}"

[api.onemklXher2k.argtypes]
6 = "T"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "T"
12 = "ZePtr{T}"

[api.onemklXgbmv.argtypes]
7 = "T"
8 = "ZePtr{T}"
10 = "ZePtr{T}"
12 = "T"
13 = "ZePtr{T}"

[api.onemklXgemv.argtypes]
5 = "T"
6 = "ZePtr{T}"
8 = "ZePtr{T}"
10 = "T"
11 = "ZePtr{T}"

[api.onemklXdot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"
7 = "RefOrZeRef{T}"

[api.onemklXdotc.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"
7 = "RefOrZeRef{T}"

[api.onemklXdotu.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"
7 = "RefOrZeRef{T}"

[api.onemklXasum.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklCasum.argtypes]
3 = "ZePtr{ComplexF32}"
5 = "ZePtr{Cfloat}"

[api.onemklZasum.argtypes]
3 = "ZePtr{ComplexF64}"
5 = "ZePtr{Float64}"

[api.onemklXaxpy.argtypes]
3 = "T"
4 = "ZePtr{T}"
6 = "ZePtr{T}"

[api.onemklXaxpby.argtypes]
3 = "T"
4 = "ZePtr{T}"
6 = "T"
7 = "ZePtr{T}"

[api.onemklXrot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXDrot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXSrot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXscal.argtypes]
3 = "T"
4 = "ZePtr{T}"

[api.onemklXDscal.argtypes]
4 = "ZePtr{T}"

[api.onemklXSscal.argtypes]
4 = "ZePtr{T}"

[api.onemklXger.argtypes]
4 = "T"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXgerc.argtypes]
4 = "T"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXhemv.argtypes]
4 = "T"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "T"
10 = "ZePtr{T}"

[api.onemklXhbmv.argtypes]
5 = "T"
6 = "ZePtr{T}"
8 = "ZePtr{T}"
10 = "T"
11 = "ZePtr{T}"

[api.onemklXher.argtypes]
4 = "T"
5 = "ZePtr{T}"
7 = "ZePtr{T}"

[api.onemklXher2.argtypes]
4 = "T"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXsbmv.argtypes]
5 = "T"
6 = "ZePtr{T}"
8 = "ZePtr{T}"
10 = "T"
11 = "ZePtr{T}"

[api.onemklXsymv.argtypes]
4 = "T"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "T"
10 = "ZePtr{T}"

[api.onemklXsyr.argtypes]
4 = "T"
5 = "ZePtr{T}"
7 = "ZePtr{T}"

[api.onemklXtbmv.argtypes]
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXtrmv.argtypes]
6 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklXtrsv.argtypes]
6 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklXnrm2.argtypes]
3 = "ZePtr{T}"
5 = "RefOrZeRef{T}"

[api.onemklCnrm2.argtypes]
3 = "ZePtr{ComplexF32}"
5 = "RefOrZeRef{Cfloat}"

[api.onemklZnrm2.argtypes]
3 = "ZePtr{ComplexF64}"
5 = "RefOrZeRef{Cdouble}"

[api.onemklXcopy.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXiamax.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{Int64}"

[api.onemklXiamax_64.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{Int64}"

[api.onemklXiamin.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{Int64}"

[api.onemklXiamin_64.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{Int64}"

[api.onemklXswap.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXsparse_set_csr_data.argtypes]
6 = "ZePtr{Int32}"
7 = "ZePtr{Int32}"
8 = "ZePtr{T}"

[api.onemklXsparse_set_csr_data_64.argtypes]
6 = "ZePtr{Int64}"
7 = "ZePtr{Int64}"
8 = "ZePtr{T}"

[api.onemklSsparse_gemv.argtypes]
3 = "Float32"
5 = "ZePtr{Float32}"
6 = "Float32"
7 = "ZePtr{Float32}"

[api.onemklDsparse_gemv.argtypes]
3 = "Float64"
5 = "ZePtr{Float64}"
6 = "Float64"
7 = "ZePtr{Float64}"

[api.onemklCsparse_gemv.argtypes]
3 = "ComplexF32"
5 = "ZePtr{ComplexF32}"
6 = "ComplexF32"
7 = "ZePtr{ComplexF32}"

[api.onemklZsparse_gemv.argtypes]
3 = "ComplexF64"
5 = "ZePtr{ComplexF64}"
6 = "ComplexF64"
7 = "ZePtr{ComplexF64}"

[api.onemklSsparse_symv.argtypes]
3 = "Float32"
5 = "ZePtr{Float32}"
6 = "Float32"
7 = "ZePtr{Float32}"

[api.onemklDsparse_symv.argtypes]
3 = "Float64"
5 = "ZePtr{Float64}"
6 = "Float64"
7 = "ZePtr{Float64}"

[api.onemklCsparse_symv.argtypes]
3 = "ComplexF32"
5 = "ZePtr{ComplexF32}"
6 = "ComplexF32"
7 = "ZePtr{ComplexF32}"

[api.onemklZsparse_symv.argtypes]
3 = "ComplexF64"
5 = "ZePtr{ComplexF64}"
6 = "ComplexF64"
7 = "ZePtr{ComplexF64}"

[api.onemklSsparse_trmv.argtypes]
5 = "Float32"
7 = "ZePtr{Float32}"
8 = "Float32"
9 = "ZePtr{Float32}"

[api.onemklDsparse_trmv.argtypes]
5 = "Float64"
7 = "ZePtr{Float64}"
8 = "Float64"
9 = "ZePtr{Float64}"

[api.onemklCsparse_trmv.argtypes]
5 = "ComplexF32"
7 = "ZePtr{ComplexF32}"
8 = "ComplexF32"
9 = "ZePtr{ComplexF32}"

[api.onemklZsparse_trmv.argtypes]
5 = "ComplexF64"
7 = "ZePtr{ComplexF64}"
8 = "ComplexF64"
9 = "ZePtr{ComplexF64}"

[api.onemklXsparse_trsv.argtypes]
7 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklSsparse_gemm.argtypes]
5 = "Float32"
7 = "ZePtr{Float32}"
10 = "Float32"
11 = "ZePtr{Float32}"

[api.onemklDsparse_gemm.argtypes]
5 = "Float64"
7 = "ZePtr{Float64}"
10 = "Float64"
11 = "ZePtr{Float64}"

[api.onemklCsparse_gemm.argtypes]
5 = "ComplexF32"
7 = "ZePtr{ComplexF32}"
10 = "ComplexF32"
11 = "ZePtr{ComplexF32}"

[api.onemklZsparse_gemm.argtypes]
5 = "ComplexF64"
7 = "ZePtr{ComplexF64}"
10 = "ComplexF64"
11 = "ZePtr{ComplexF64}"
