[general]
library_name = "liboneapi_support"
output_file_path = "../lib/support/liboneapi_support.jl"


[codegen]
use_ccall_macro = true

[api.onemklXgemmBatched.argtypes]
4 = "ZePtr{Int64}"
5 = "ZePtr{Int64}"
6 = "ZePtr{Int64}"
7 = "ZePtr{T}"
8 = "ZePtr{Ptr{T}}"
9 = "ZePtr{Int64}"
10 = "ZePtr{Ptr{T}}"
11 = "ZePtr{Int64}"
12 = "ZePtr{T}"
13 = "ZePtr{Ptr{T}}"
14 = "ZePtr{Int64}"
16 = "ZePtr{Int64}"

[api.onemklXtrsmBatched.argtypes]
6 = "ZePtr{Int64}"
7 = "ZePtr{Int64}"
8 = "ZePtr{T}"
9 = "ZePtr{Ptr{T}}"
10 = "ZePtr{Int64}"
11 = "ZePtr{Ptr{T}}"
12 = "ZePtr{Int64}"
14 = "ZePtr{Int64}"

[api.onemklXgemmBatchStrided.argtypes]
7 = "Ref{T}"
8 = "ZePtr{T}"
11 = "ZePtr{T}"
14 = "Ref{T}"
15 = "ZePtr{T}"

[api.onemklXgemm.argtypes]
7 = "Ref{T}"
8 = "ZePtr{T}"
10 = "ZePtr{T}"
12 = "Ref{T}"
13 = "ZePtr{T}"

[api.onemklXsymm.argtypes]
6 = "Ref{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "Ref{T}"
12 = "ZePtr{T}"

[api.onemklXsyrk.argtypes]
6 = "Ref{T}"
7 = "ZePtr{T}"
9 = "Ref{T}"
10 = "ZePtr{T}"

[api.onemklXsyr2k.argtypes]
6 = "Ref{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "Ref{T}"
12 = "ZePtr{T}"

[api.onemklXtrmm.argtypes]
8 = "Ref{T}"
9 = "ZePtr{T}"
11 = "ZePtr{T}"

[api.onemklXtrsm.argtypes]
8 = "Ref{T}"
9 = "ZePtr{T}"
11 = "ZePtr{T}"

[api.onemklXhemm.argtypes]
6 = "Ref{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "Ref{T}"
12 = "ZePtr{T}"

[api.onemklXherk.argtypes]
6 = "Ref{T}"
7 = "ZePtr{T}"
9 = "Ref{T}"
10 = "ZePtr{T}"

[api.onemklXher2k.argtypes]
6 = "Ref{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"
11 = "Ref{T}"
12 = "ZePtr{T}"

[api.onemklXgbmv.argtypes]
7 = "Ref{T}"
8 = "ZePtr{T}"
10 = "ZePtr{T}"
12 = "Ref{T}"
13 = "ZePtr{T}"

[api.onemklXgemv.argtypes]
5 = "Ref{T}"
6 = "ZePtr{T}"
8 = "ZePtr{T}"
10 = "Ref{T}"
11 = "ZePtr{T}"

[api.onemklXdot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"
7 = "RefOrZeRef{T}"

[api.onemklXdotc.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"
7 = "RefOrZeRef{T}"

[api.onemklXdotu.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"
7 = "RefOrZeRef{T}"

[api.onemklXasum.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklCasum.argtypes]
3 = "ZePtr{ComplexF32}"
5 = "ZePtr{Cfloat}"

[api.onemklZasum.argtypes]
3 = "ZePtr{ComplexF64}"
5 = "ZePtr{Float64}"

[api.onemklXaxpy.argtypes]
3 = "Ref{T}"
4 = "ZePtr{T}"
6 = "ZePtr{T}"

[api.onemklXaxpby.argtypes]
3 = "Ref{T}"
4 = "ZePtr{T}"
6 = "Ref{T}"
7 = "ZePtr{T}"

[api.onemklXrot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXDrot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXSrot.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXscal.argtypes]
3 = "Ref{T}"
4 = "ZePtr{T}"

[api.onemklXDscal.argtypes]
4 = "ZePtr{T}"

[api.onemklXSscal.argtypes]
4 = "ZePtr{T}"

[api.onemklXger.argtypes]
4 = "Ref{T}"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXgerc.argtypes]
4 = "Ref{T}"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXhemv.argtypes]
4 = "Ref{T}"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "Ref{T}"
10 = "ZePtr{T}"

[api.onemklXhbmv.argtypes]
5 = "Ref{T}"
6 = "ZePtr{T}"
8 = "ZePtr{T}"
10 = "Ref{T}"
11 = "ZePtr{T}"

[api.onemklXher.argtypes]
4 = "Ref{T}"
5 = "ZePtr{T}"
7 = "ZePtr{T}"

[api.onemklXher2.argtypes]
4 = "Ref{T}"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXsbmv.argtypes]
5 = "Ref{T}"
6 = "ZePtr{T}"
8 = "ZePtr{T}"
10 = "Ref{T}"
11 = "ZePtr{T}"

[api.onemklXsymv.argtypes]
4 = "Ref{T}"
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "Ref{T}"
10 = "ZePtr{T}"

[api.onemklXsyr.argtypes]
4 = "Ref{T}"
5 = "ZePtr{T}"
7 = "ZePtr{T}"

[api.onemklXtbmv.argtypes]
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXtrmv.argtypes]
6 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklXtrsv.argtypes]
6 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklXnrm2.argtypes]
3 = "ZePtr{T}"
5 = "RefOrZeRef{T}"

[api.onemklCnrm2.argtypes]
3 = "ZePtr{ComplexF32}"
5 = "RefOrZeRef{Cfloat}"

[api.onemklZnrm2.argtypes]
3 = "ZePtr{ComplexF64}"
5 = "RefOrZeRef{Cdouble}"

[api.onemklXcopy.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXiamax.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{Int64}"

[api.onemklXiamin.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{Int64}"

[api.onemklXswap.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{T}"

[api.onemklXdgmm.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXgeru.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXsparse_set_csr_data.argtypes]
6 = "ZePtr{Int32}"
7 = "ZePtr{Int32}"
8 = "ZePtr{T}"

[api.onemklXsparse_set_csr_data_64.argtypes]
6 = "ZePtr{Int64}"
7 = "ZePtr{Int64}"
8 = "ZePtr{T}"

[api.onemklSsparse_gemv.argtypes]
3 = "Ref{Float32}"
5 = "ZePtr{Float32}"
6 = "Ref{Float32}"
7 = "ZePtr{Float32}"

[api.onemklDsparse_gemv.argtypes]
3 = "Ref{Float64}"
5 = "ZePtr{Float64}"
6 = "Ref{Float64}"
7 = "ZePtr{Float64}"

[api.onemklCsparse_gemv.argtypes]
3 = "Ref{ComplexF32}"
5 = "ZePtr{ComplexF32}"
6 = "Ref{ComplexF32}"
7 = "ZePtr{ComplexF32}"

[api.onemklZsparse_gemv.argtypes]
3 = "Ref{ComplexF64}"
5 = "ZePtr{ComplexF64}"
6 = "Ref{ComplexF64}"
7 = "ZePtr{ComplexF64}"

[api.onemklSsparse_symv.argtypes]
3 = "Ref{Float32}"
5 = "ZePtr{Float32}"
6 = "Ref{Float32}"
7 = "ZePtr{Float32}"

[api.onemklDsparse_symv.argtypes]
3 = "Ref{Float64}"
5 = "ZePtr{Float64}"
6 = "Ref{Float64}"
7 = "ZePtr{Float64}"

[api.onemklCsparse_symv.argtypes]
3 = "Ref{ComplexF32}"
5 = "ZePtr{ComplexF32}"
6 = "Ref{ComplexF32}"
7 = "ZePtr{ComplexF32}"

[api.onemklZsparse_symv.argtypes]
3 = "Ref{ComplexF64}"
5 = "ZePtr{ComplexF64}"
6 = "Ref{ComplexF64}"
7 = "ZePtr{ComplexF64}"

[api.onemklSsparse_trmv.argtypes]
5 = "Ref{Float32}"
7 = "ZePtr{Float32}"
8 = "Ref{Float32}"
9 = "ZePtr{Float32}"

[api.onemklDsparse_trmv.argtypes]
5 = "Ref{Float64}"
7 = "ZePtr{Float64}"
8 = "Ref{Float64}"
9 = "ZePtr{Float64}"

[api.onemklCsparse_trmv.argtypes]
5 = "Ref{ComplexF32}"
7 = "ZePtr{ComplexF32}"
8 = "Ref{ComplexF32}"
9 = "ZePtr{ComplexF32}"

[api.onemklZsparse_trmv.argtypes]
5 = "Ref{ComplexF64}"
7 = "ZePtr{ComplexF64}"
8 = "Ref{ComplexF64}"
9 = "ZePtr{ComplexF64}"

[api.onemklXsparse_trsv.argtypes]
6 = "ZePtr{T}"
7 = "ZePtr{T}"

[api.onemklSsparse_gemm.argtypes]
5 = "Ref{Float32}"
7 = "ZePtr{Float32}"
10 = "Ref{Float32}"
11 = "ZePtr{Float32}"

[api.onemklDsparse_gemm.argtypes]
5 = "Ref{Float64}"
7 = "ZePtr{Float64}"
10 = "Ref{Float64}"
11 = "ZePtr{Float64}"

[api.onemklCsparse_gemm.argtypes]
5 = "Ref{ComplexF32}"
7 = "ZePtr{ComplexF32}"
10 = "Ref{ComplexF32}"
11 = "ZePtr{ComplexF32}"

[api.onemklZsparse_gemm.argtypes]
5 = "Ref{ComplexF64}"
7 = "ZePtr{ComplexF64}"
10 = "Ref{ComplexF64}"
11 = "ZePtr{ComplexF64}"

[api.onemklXsparse_update_diagonal_values.argtypes]
4 = "ZePtr{T}"

[api.onemklSsparse_gemvdot.argtypes]
5 = "ZePtr{Float32}"
6 = "Ref{Float32}"
7 = "ZePtr{Float32}"
8 = "ZePtr{Float32}"

[api.onemklDsparse_gemvdot.argtypes]
5 = "ZePtr{Float64}"
6 = "Ref{Float64}"
7 = "ZePtr{Float64}"
8 = "ZePtr{Float64}"

[api.onemklCsparse_gemvdot.argtypes]
5 = "ZePtr{ComplexF32}"
6 = "Ref{ComplexF32}"
7 = "ZePtr{ComplexF32}"
8 = "ZePtr{ComplexF32}"

[api.onemklZsparse_gemvdot.argtypes]
5 = "ZePtr{ComplexF64}"
6 = "Ref{ComplexF64}"
7 = "ZePtr{ComplexF64}"
8 = "ZePtr{ComplexF64}"

[api.onemklXsparse_matmat.argtypes]
8 = "ZePtr{Cvoid}"

[api.onemklXpotrf.argtypes]
4 = "ZePtr{T}"
6 = "ZePtr{T}"

[api.onemklXpotrs.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXpotri.argtypes]
4 = "ZePtr{T}"
6 = "ZePtr{T}"

[api.onemklXsytrf.argtypes]
4 = "ZePtr{T}"
6 = "ZePtr{Int64}"
7 = "ZePtr{T}"

[api.onemklXgetrf.argtypes]
4 = "ZePtr{T}"
6 = "ZePtr{Int64}"
7 = "ZePtr{T}"

[api.onemklXgetrs.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{Int64}"
8 = "ZePtr{T}"
10 = "ZePtr{T}"

[api.onemklXgetri.argtypes]
3 = "ZePtr{T}"
5 = "ZePtr{Int64}"
6 = "ZePtr{T}"

[api.onemklXgeqrf.argtypes]
4 = "ZePtr{T}"
6 = "ZePtr{T}"
7 = "ZePtr{T}"

[api.onemklXormqr.argtypes]
7 = "ZePtr{T}"
9 = "ZePtr{T}"
10 = "ZePtr{T}"
12 = "ZePtr{T}"

[api.onemklXunmqr.argtypes]
7 = "ZePtr{T}"
9 = "ZePtr{T}"
10 = "ZePtr{T}"
12 = "ZePtr{T}"

[api.onemklXorgqr.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklXungqr.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklSgebrd.argtypes]
4 = "ZePtr{Float32}"
6 = "ZePtr{Float32}"
7 = "ZePtr{Float32}"
8 = "ZePtr{Float32}"
9 = "ZePtr{Float32}"
10 = "ZePtr{Float32}"

[api.onemklDgebrd.argtypes]
4 = "ZePtr{Float64}"
6 = "ZePtr{Float64}"
7 = "ZePtr{Float64}"
8 = "ZePtr{Float64}"
9 = "ZePtr{Float64}"
10 = "ZePtr{Float64}"

[api.onemklCgebrd.argtypes]
4 = "ZePtr{ComplexF32}"
6 = "ZePtr{Float32}"
7 = "ZePtr{ComplexF32}"
8 = "ZePtr{ComplexF32}"
9 = "ZePtr{ComplexF32}"
10 = "ZePtr{ComplexF32}"

[api.onemklZgebrd.argtypes]
4 = "ZePtr{ComplexF64}"
6 = "ZePtr{Float64}"
7 = "ZePtr{ComplexF64}"
8 = "ZePtr{ComplexF64}"
9 = "ZePtr{ComplexF64}"
10 = "ZePtr{ComplexF64}"

[api.onemklSgesvd.argtypes]
6 = "ZePtr{Float32}"
8 = "ZePtr{Float32}"
9 = "ZePtr{Float32}"
11 = "ZePtr{Float32}"
13 = "ZePtr{Float32}"

[api.onemklDgesvd.argtypes]
6 = "ZePtr{Float64}"
8 = "ZePtr{Float64}"
9 = "ZePtr{Float64}"
11 = "ZePtr{Float64}"
13 = "ZePtr{Float64}"

[api.onemklCgesvd.argtypes]
6 = "ZePtr{ComplexF32}"
8 = "ZePtr{Float32}"
9 = "ZePtr{ComplexF32}"
11 = "ZePtr{ComplexF32}"
13 = "ZePtr{ComplexF32}"

[api.onemklZgesvd.argtypes]
6 = "ZePtr{ComplexF64}"
8 = "ZePtr{Float64}"
9 = "ZePtr{ComplexF64}"
11 = "ZePtr{ComplexF64}"
13 = "ZePtr{ComplexF64}"

[api.onemklXtrtri.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{T}"

[api.onemklXgesv.argtypes]
4 = "ZePtr{T}"
6 = "ZePtr{T}"
7 = "ZePtr{T}"
9 = "ZePtr{T}"

[api.onemklXgetrf_batch.argtypes]
4 = "ZePtr{Ptr{T}}"
6 = "ZePtr{Ptr{Int64}}"
9 = "ZePtr{T}"

[api.onemklXgetrs_batch.argtypes]
5 = "ZePtr{Ptr{T}}"
7 = "ZePtr{Ptr{Int64}}"
8 = "ZePtr{Ptr{T}}"
12 = "ZePtr{T}"

[api.onemklXgetri_batch.argtypes]
3 = "ZePtr{Ptr{T}}"
5 = "ZePtr{Ptr{Int64}}"
8 = "ZePtr{T}"

[api.onemklXgeqrf_batch.argtypes]
4 = "ZePtr{Ptr{T}}"
6 = "ZePtr{Ptr{T}}"
9 = "ZePtr{T}"

[api.onemklXorgqr_batch.argtypes]
5 = "ZePtr{Ptr{T}}"
7 = "ZePtr{Ptr{T}}"
10 = "ZePtr{T}"

[api.onemklXungqr_batch.argtypes]
5 = "ZePtr{Ptr{T}}"
7 = "ZePtr{Ptr{T}}"
10 = "ZePtr{T}"

[api.onemklXpotrf_batch.argtypes]
4 = "ZePtr{Ptr{T}}"
8 = "ZePtr{T}"

[api.onemklXpotrs_batch.argtypes]
5 = "ZePtr{Ptr{T}}"
7 = "ZePtr{Ptr{T}}"
11 = "ZePtr{T}"

[api.onemklXsyevd.argtypes]
5 = "ZePtr{T}"
7 = "ZePtr{T}"
8 = "ZePtr{T}"

[api.onemklCheevd.argtypes]
5 = "ZePtr{ComplexF32}"
7 = "ZePtr{Float32}"
8 = "ZePtr{ComplexF32}"

[api.onemklZheevd.argtypes]
5 = "ZePtr{ComplexF64}"
7 = "ZePtr{Float64}"
8 = "ZePtr{ComplexF64}"

[api.onemklXsygvd.argtypes]
6 = "ZePtr{T}"
8 = "ZePtr{T}"
10 = "ZePtr{T}"
11 = "ZePtr{T}"

[api.onemklChegvd.argtypes]
6 = "ZePtr{ComplexF32}"
8 = "ZePtr{ComplexF32}"
10 = "ZePtr{Float32}"
11 = "ZePtr{ComplexF32}"

[api.onemklZhegvd.argtypes]
6 = "ZePtr{ComplexF64}"
8 = "ZePtr{ComplexF64}"
10 = "ZePtr{Float64}"
11 = "ZePtr{ComplexF64}"
