steps:
  # Test supported Julia versions
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "Julia 1.6"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.6
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        command: |
          julia --project=deps deps/build_ci.jl
        agents:
          queue: "juliagpu"
          intel: "*"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 60

      - label: "Julia 1.7"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.7
          - JuliaCI/julia-test#v1: ~
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        command: |
          julia --project=deps deps/build_ci.jl
        agents:
          queue: "juliagpu"
          intel: "*"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60

      - label: "Julia 1.8"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.8
          - JuliaCI/julia-test#v1: ~
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        command: |
          julia --project=deps deps/build_ci.jl
        agents:
          queue: "juliagpu"
          intel: "*"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60

  # Special tests
  - group: ":eyes: Special"
    depends_on: "julia"
    steps:
      - label: "Validation"
        plugins:
          - JuliaCI/julia#v1:
              version: 1.6
          - JuliaCI/julia-test#v1:
              julia_args: "-g2"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - lib
                - examples
        command: |
          julia --project=deps deps/build_ci.jl
        env:
          ZE_ENABLE_VALIDATION_LAYER: '1'
          ZE_ENABLE_PARAMETER_VALIDATION: '1'
        agents:
          queue: "juliagpu"
          intel: "*"
        if: build.message !~ /\[skip tests\]/ && !build.pull_request.draft
        timeout_in_minutes: 60

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  SECRET_CODECOV_TOKEN: "OYpS8fj3vGhj7iZf9vLAeapyxQNSOEW6mApcSvGboL9AlS+0nfOSFjFrIBNnIU0prxQQy1gR9AwR/JO1m2OFWeRhjYtkQPPhk4xVtSKmv0LLTL0snA8IohUopqfu722i7zLrPcz/A0LFIFsb0ey+oReJs2xnGOshNIJu4FDowUV3wmZvfKWNsSK4cGN+HFQ3387Ow4SsmiUr7oqh0iMBQNqaY8oZ2BY1dFOgPaOegIp70YEFRdJ8DKaLd7WGxFLY9oQEhZZdmx/zx0xo56/NGtDwVYkDPa4qPhJczDBoIn5XvcRiIW0VJ/MaRARxnpenBX5H6gwdcZYUGtjXWIRXBw==;U2FsdGVkX1/bZy1Bp4/dBH5scPpWqLKusXGvSkRGUa+1F7hi4P4Cu5a6GcfNIEvQr+bBj2VlZvqhNW0FAqN3QQ=="
