env:
  SECRET_CODECOV_TOKEN: "OYpS8fj3vGhj7iZf9vLAeapyxQNSOEW6mApcSvGboL9AlS+0nfOSFjFrIBNnIU0prxQQy1gR9AwR/JO1m2OFWeRhjYtkQPPhk4xVtSKmv0LLTL0snA8IohUopqfu722i7zLrPcz/A0LFIFsb0ey+oReJs2xnGOshNIJu4FDowUV3wmZvfKWNsSK4cGN+HFQ3387Ow4SsmiUr7oqh0iMBQNqaY8oZ2BY1dFOgPaOegIp70YEFRdJ8DKaLd7WGxFLY9oQEhZZdmx/zx0xo56/NGtDwVYkDPa4qPhJczDBoIn5XvcRiIW0VJ/MaRARxnpenBX5H6gwdcZYUGtjXWIRXBw==;U2FsdGVkX1/bZy1Bp4/dBH5scPpWqLKusXGvSkRGUa+1F7hi4P4Cu5a6GcfNIEvQr+bBj2VlZvqhNW0FAqN3QQ=="

steps:
  # Julia versions

  - label: "Julia 1.5"
    plugins:
      - JuliaCI/julia#v0.2:
          version: 1.5
      - JuliaCI/julia-test#v0.2: ~
      - JuliaCI/julia-coverage#v0.2:
          codecov: true
          dirs:
            - src
            - lib
            - examples
    agents:
      queue: "juliagpu"
      intel: "*"


  # Special tests

  - label: "debug"
    plugins:
      - JuliaCI/julia#v0.2:
          version: 1.5
      - JuliaCI/julia-test#v0.2:
          julia_args: "-g2"
      - JuliaCI/julia-coverage#v0.2:
          codecov: true
          dirs:
            - src
            - lib
            - examples
    env:
      ZE_ENABLE_VALIDATION_LAYER: '1'
      ZE_ENABLE_PARAMETER_VALIDATION: '1'
    agents:
      queue: "juliagpu"
      intel: "*"
